### PR TITLE
Fix serviceConfig within scope of copy

### LINKED ISSUE #210: serviceConfig should be involved in the copy() of GrpcClientProperties
The newly added serviceConfig field in the ChannelConfig class was not copied in the copy() method, which causes the copied object to lose the service configuration.

### PR DESCRIPTION
**Pull request by NeatGuyCoding**
Fix #210

### CODE REVIEW

**Comment by onobc** [comment]
Hi @NeatGuyCoding , good catch and thank you for the contribution. Can you please follow [these instructions](https://github.com/spring-projects/spring-grpc/pull/211/checks?check_run_id=45031342353) and sign the commit and we will get it merged after that? Thanks

File: spring-grpc-spring-boot-autoconfigure/src/main/java/org/springframework/grpc/autoconfigure/client/GrpcClientProperties.java [hunk 1]
```diff
@@ -349,6 +349,8 @@ public ChannelConfig copy() {
 			copy.defaultDeadline = this.defaultDeadline;
 			copy.health.copyValuesFrom(this.getHealth());
 			copy.ssl.copyValuesFrom(this.getSsl());
+			copy.serviceConfig.clear();
```
Comment (onobc) [inline spring-grpc-spring-boot-autoconfigure/src/main/java/org/springframework/grpc/autoconfigure/client/GrpcClientProperties.java:352]: I think we can drop this `clear` call.

Comment (NeatGuyCoding) [reply spring-grpc-spring-boot-autoconfigure/src/main/java/org/springframework/grpc/autoconfigure/client/GrpcClientProperties.java:352]: ok, I will fix this

**Comment by NeatGuyCoding** [comment]
all fixed, thanks a lot @onobc
